"""Drift and validation tests for generated skill artifacts (the committed discovery copy
and the skill frontmatter). Regenerate with `make gen-skill` if the drift test fails."""

import re
from pathlib import Path

import pytest

from flowmark import reformat_text
from flowmark.skill import (
    DISCOVERY_VERSION,
    FLOWMARK_RS_DISCOVERY_VERSION,
    compose_skill,
    discovery_project_setup_text,
    discovery_skill_text,
    is_pypi_release,
)

REPO_ROOT = Path(__file__).resolve().parents[1]
DISCOVERY_COPY = REPO_ROOT / "skills" / "flowmark" / "SKILL.md"
DISCOVERY_REFERENCE = REPO_ROOT / "skills" / "flowmark" / "references" / "project-setup.md"
README = REPO_ROOT / "README.md"

# Artifacts whose runner-pin examples are consumed by users/agents and must all pin the
# single source of truth, DISCOVERY_VERSION. All are regenerated by `make format`:
#   - README.md (from docs/shared via generate-python-readme.py)
#   - skills/flowmark/SKILL.md (published discovery copy, from skill.py)
#   - this repo's own installed skill surfaces (dogfood, via `flowmark --install-skill`):
#     the portable and Claude SKILL.md mirrors and the AGENTS.md flowmark block.
_PINNED_ARTIFACTS = [
    README,
    DISCOVERY_COPY,
    REPO_ROOT / ".agents" / "skills" / "flowmark" / "SKILL.md",
    REPO_ROOT / ".claude" / "skills" / "flowmark" / "SKILL.md",
    REPO_ROOT / "AGENTS.md",
]

# Shipped docs and skill resources that carry the recommended Rust-port
# `flowmark-rs==` pin.
_RS_PINNED_ARTIFACTS = [
    README,
    DISCOVERY_COPY,
    DISCOVERY_REFERENCE,
    REPO_ROOT / ".agents" / "skills" / "flowmark" / "SKILL.md",
    REPO_ROOT / ".agents" / "skills" / "flowmark" / "references" / "project-setup.md",
    REPO_ROOT / ".claude" / "skills" / "flowmark" / "SKILL.md",
    REPO_ROOT / ".claude" / "skills" / "flowmark" / "references" / "project-setup.md",
    REPO_ROOT / "AGENTS.md",
]

# A concrete `flowmark==<version>` pin (digit-led), ignoring intentionally-generic
# `flowmark==<X.Y.Z>` / `flowmark==<version>` placeholder examples in prose. The trailing
# `(?!-)` keeps it from matching the `flowmark` prefix of a `flowmark-rs==` pin.
_CONCRETE_PIN_RE = re.compile(r"flowmark==(\d[^\s`)\"']*)")
# A concrete `flowmark-rs==<version>` pin (the recommended fast Rust port).
_CONCRETE_RS_PIN_RE = re.compile(r"flowmark-rs==(\d[^\s`)\"']*)")


def test_discovery_copy_matches_generator() -> None:
    """The committed repo-root discovery copy must match the generator output."""
    assert DISCOVERY_COPY.read_text(encoding="utf-8") == discovery_skill_text()
    assert DISCOVERY_REFERENCE.read_text(encoding="utf-8") == discovery_project_setup_text()


def test_discovery_copy_is_flowmark_stable() -> None:
    """`flowmark --auto` over the discovery copy must be a no-op (it lives under `skills/`)."""
    text = DISCOVERY_COPY.read_text(encoding="utf-8")
    assert reformat_text(text) == text
    reference = DISCOVERY_REFERENCE.read_text(encoding="utf-8")
    assert reformat_text(reference) == reference


def test_discovery_skill_bundles_its_project_setup_reference() -> None:
    text = DISCOVERY_COPY.read_text(encoding="utf-8")
    assert "references/project-setup.md" in text
    assert DISCOVERY_REFERENCE.is_file()


def test_project_setup_hooks_cover_common_markdown_extensions() -> None:
    reference = DISCOVERY_REFERENCE.read_text(encoding="utf-8")
    assert 'glob: "*.{md,mdc,markdown}"' in reference
    assert "files: '\\.(md|mdc|markdown)$'" in reference


@pytest.mark.parametrize("artifact", _PINNED_ARTIFACTS, ids=lambda p: p.name)
def test_shipped_artifacts_pin_discovery_version(artifact: Path) -> None:
    """Every concrete `flowmark==` pin in a shipped artifact equals DISCOVERY_VERSION.

    All runner-pin examples derive from the one source of truth (DISCOVERY_VERSION), so a
    release bump that re-runs `make format` updates them together. This catches the
    failure mode where one location is bumped (or regenerated) but another is left stale.
    """
    text = artifact.read_text(encoding="utf-8")
    pins = _CONCRETE_PIN_RE.findall(text)
    assert pins, f"{artifact.name} has no concrete flowmark== pin to check"
    stale = sorted({p for p in pins if p != DISCOVERY_VERSION})
    assert not stale, (
        f"{artifact.name} pins {stale} but DISCOVERY_VERSION is {DISCOVERY_VERSION!r}; "
        "bump DISCOVERY_VERSION and re-run `make format` (see docs/publishing.md)"
    )


@pytest.mark.parametrize("artifact", _RS_PINNED_ARTIFACTS, ids=lambda p: p.name)
def test_shipped_artifacts_pin_rs_discovery_version(artifact: Path) -> None:
    """Every `flowmark-rs==` pin in a skill surface equals FLOWMARK_RS_DISCOVERY_VERSION.

    The Rust port is the recommended default; its pin is a separate source of truth from
    the Python DISCOVERY_VERSION (the packages are numbered independently), so this guards
    against a stale or mismatched Rust pin slipping into one surface.
    """
    text = artifact.read_text(encoding="utf-8")
    pins = _CONCRETE_RS_PIN_RE.findall(text)
    assert pins, f"{artifact.name} has no concrete flowmark-rs== pin to check"
    stale = sorted({p for p in pins if p != FLOWMARK_RS_DISCOVERY_VERSION})
    assert not stale, (
        f"{artifact.name} pins flowmark-rs {stale} but FLOWMARK_RS_DISCOVERY_VERSION is "
        f"{FLOWMARK_RS_DISCOVERY_VERSION!r}; bump it and re-run `make format`"
    )


def test_rs_discovery_version_is_resolvable() -> None:
    """The recommended Rust-port pin must be a real, PyPI-installable release."""
    assert is_pypi_release(FLOWMARK_RS_DISCOVERY_VERSION)


@pytest.mark.parametrize("artifact", _PINNED_ARTIFACTS, ids=lambda p: p.name)
def test_shipped_artifacts_never_use_at_latest(artifact: Path) -> None:
    """Shipped runner examples must pin a version, never an unpinned `@latest`.

    Mentions warning *against* `@latest` are fine; an actual `uvx flowmark@latest`
    invocation is not (it silently drifts and defeats the supply-chain pin). The same
    holds for the recommended Rust port, `flowmark-rs`.
    """
    text = artifact.read_text(encoding="utf-8")
    assert "uvx flowmark@latest" not in text
    assert "uvx --from flowmark@latest" not in text
    assert "uvx flowmark-rs@latest" not in text
    assert "uvx --from flowmark-rs@latest" not in text


def test_discovery_copy_has_resolvable_version_pin() -> None:
    """The committed discovery copy must pin a real, PyPI-installable version.

    `npx skills add jlevy/flowmark@flowmark` users have no other source of truth for the
    bootstrap invocation, so a `<version>` placeholder or `.dev`/local-suffix pin
    in the committed copy would silently break the cross-agent install promise in
    the README.
    """
    text = DISCOVERY_COPY.read_text(encoding="utf-8")
    # Neither placeholder may survive past compose.
    assert "__FLOWMARK_VERSION__" not in text
    assert "__FLOWMARK_RS_VERSION__" not in text
    assert "flowmark==<version>" not in text  # not a literal placeholder
    pin = re.search(r"flowmark==([^\s`)\"']+)", text)
    assert pin is not None, "discovery copy missing a flowmark== version pin"
    pin_value = pin.group(1)
    assert ".dev" not in pin_value and "+" not in pin_value, (
        f"discovery copy pin {pin_value!r} is a dev/local version, not PyPI-installable; "
        "bump DISCOVERY_VERSION to a real release and re-run `make format`"
    )
    rs_pin = re.search(r"flowmark-rs==([^\s`)\"']+)", text)
    assert rs_pin is not None, "discovery copy missing a flowmark-rs== version pin"
    rs_value = rs_pin.group(1)
    assert ".dev" not in rs_value and "+" not in rs_value, (
        f"discovery copy Rust pin {rs_value!r} is a dev/local version, not PyPI-installable"
    )


def test_discovery_copy_references_both_packages() -> None:
    """The skill recommends the Rust port and offers the Python build, so the discovery
    copy must name and link both packages."""
    text = DISCOVERY_COPY.read_text(encoding="utf-8")
    assert "github.com/jlevy/flowmark-rs" in text
    assert "github.com/jlevy/flowmark)" in text  # the Python package link
    assert "uvx --from flowmark-rs==" in text
    assert "uvx --from flowmark==" in text


def test_skill_frontmatter_is_valid() -> None:
    content = compose_skill("1.2.3")
    assert content.startswith("---\n")
    frontmatter = content[4 : content.index("\n---\n", 4)]
    assert re.search(r"^name: flowmark$", frontmatter, re.M)
    description = re.search(r"^description: (.+)$", frontmatter, re.M)
    assert description is not None
    assert len(description.group(1)) <= 1024  # Agent Skills cap (guideline §4.1)
    assert re.search(r"^allowed-tools: ", frontmatter, re.M)
