"""
Agent skill installation for flowmark.

Installs the flowmark `SKILL.md` so AI coding agents can discover and use it. By default
this installs project-locally into both the portable `.agents/skills/flowmark/` location
(read by Codex, Gemini CLI, pi) and the `.claude/skills/flowmark/` mirror (Claude Code
reads only that path). A legacy single-base install (`agent_base`, e.g. `~/.claude`) is
kept for explicit/global installs.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path
from typing import NamedTuple

# Format version for generated skill artifacts. Stamped onto install artifacts so a
# future flowmark can detect and safely upgrade older generated files (and refuse to
# clobber a newer format it doesn't understand).
SKILL_FORMAT = "f01"

# Placeholder in the authored SKILL.md, replaced by `compose_skill` with a concrete
# version pin for the local-first runner fallback (see SKILL.md).
_VERSION_PLACEHOLDER = "__FLOWMARK_VERSION__"

# Literal pin shown in committed/published artifacts (the in-repo discovery copy), where
# embedding a concrete version would churn on every release. Real installs substitute the
# installed version instead.
DOC_VERSION_PIN = "<version>"


def get_skill_content() -> str:
    """Read the authored SKILL.md template from package data.

    The returned text still contains the version placeholder; use `compose_skill` to
    render an installable/publishable copy.

    Raises:
        ImportError: If package resources cannot be accessed.
        FileNotFoundError: If SKILL.md cannot be found in package data.
    """
    # importlib.resources.files() is available in Python 3.9+
    # This project requires Python 3.10+, so no fallback needed
    from importlib.resources import files

    skill_file = files("flowmark").joinpath("skills/SKILL.md")
    return skill_file.read_text(encoding="utf-8")


def flowmark_version() -> str:
    """The installed flowmark version, or the doc placeholder if it can't be determined."""
    from importlib.metadata import PackageNotFoundError, version

    try:
        return version("flowmark")
    except PackageNotFoundError:
        return DOC_VERSION_PIN


def compose_skill(version: str | None = None) -> str:
    """
    Render the SKILL.md template into a final skill document.

    `version` is substituted into the pinned-runner fallback. Pass an explicit string
    (e.g. `DOC_VERSION_PIN` for the committed discovery copy) for a stable, drift-free
    artifact; pass `None` to pin to the installed flowmark version (used when installing
    into an agent on a user's machine). Deterministic: same inputs always yield identical
    output.
    """
    pin = flowmark_version() if version is None else version
    return get_skill_content().replace(_VERSION_PLACEHOLDER, pin)


def get_docs_content() -> str:
    """Read README.md from the repository root.

    Returns:
        The content of the README.md file as a string.
    """
    # Find README.md relative to this file (src/flowmark/skill.py -> repo root)
    current_file = Path(__file__).resolve()
    repo_root = current_file.parent.parent.parent
    readme_path = repo_root / "README.md"

    if readme_path.exists():
        return readme_path.read_text(encoding="utf-8")

    # Fallback: return basic help text with link to online docs
    return """# Flowmark Documentation

Run `flowmark --help` for command-line options.

For full documentation, visit: https://github.com/jlevy/flowmark
"""


SKILL_DIRNAME = "flowmark"
# Project-local skill surfaces, relative to the project root.
PORTABLE_SKILL_REL = Path(".agents") / "skills" / SKILL_DIRNAME
CLAUDE_SKILL_REL = Path(".claude") / "skills" / SKILL_DIRNAME

_FORMAT_RE = re.compile(r"skill-format=f(\d+)")


def _format_num() -> int:
    return int(SKILL_FORMAT.lstrip("f"))


def _generated_marker() -> str:
    return (
        f"<!-- DO NOT EDIT. Generated by `flowmark --install-skill` "
        f"(skill-format={SKILL_FORMAT}). -->"
    )


def render_skill_file(version: str | None = None) -> str:
    """
    The skill document to write to disk: `compose_skill` plus a `DO NOT EDIT` +
    format-version marker inserted after the YAML frontmatter (so frontmatter stays
    first and the marker survives a `flowmark --auto` pass).
    """
    composed = compose_skill(version)
    marker = _generated_marker()
    delimiter = "\n---\n"
    if composed.startswith("---\n") and (end := composed.find(delimiter, 4)) != -1:
        head = composed[: end + len(delimiter)]
        body = composed[end + len(delimiter) :]
        return f"{head}{marker}\n\n{body}"
    return f"{marker}\n\n{composed}"


def _existing_format(path: Path) -> int | None:
    """Format number stamped on an existing generated file; 0 if unmarked; None if absent."""
    if not path.is_file():
        return None
    match = _FORMAT_RE.search(path.read_text(encoding="utf-8"))
    return int(match.group(1)) if match else 0


class InstallResult(NamedTuple):
    surface: str
    path: Path
    # "installed" | "updated" | "unchanged" | "blocked-newer"
    action: str


def _write_surface(skill_dir: Path, surface: str, content: str) -> InstallResult:
    target = skill_dir / "SKILL.md"
    existing = _existing_format(target)
    # Forward-compatibility guard: never clobber an artifact stamped with a newer format.
    if existing is not None and existing > _format_num():
        return InstallResult(surface, target, "blocked-newer")
    if target.is_file() and target.read_text(encoding="utf-8") == content:
        return InstallResult(surface, target, "unchanged")
    action = "updated" if target.exists() else "installed"
    skill_dir.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")
    return InstallResult(surface, target, action)


def install_skill(
    agent_base: str | None = None,
    *,
    project_root: Path | str | None = None,
    claude: bool = True,
    codex: bool = True,
) -> list[InstallResult]:
    """
    Install the flowmark skill, version-pinned to the installed flowmark.

    With `agent_base` set, does a single-base install to `{agent_base}/skills/flowmark/`
    (explicit/global, e.g. `~/.claude`). Otherwise installs project-locally under
    `project_root` (default: cwd): the portable `.agents/skills/flowmark/` surface when
    `codex` is set and the `.claude/skills/flowmark/` mirror when `claude` is set.

    Idempotent (re-running an up-to-date install reports "unchanged") and returns a
    per-surface result list.
    """
    try:
        content = render_skill_file()
    except (ImportError, FileNotFoundError) as e:
        print(f"\n✗ Error: Could not load skill content: {e}", file=sys.stderr)
        print("\nThis command requires flowmark to be installed as a package.", file=sys.stderr)
        print("Install with: uv tool install flowmark", file=sys.stderr)
        sys.exit(1)

    results: list[InstallResult] = []
    try:
        if agent_base is not None:
            base = Path(agent_base).resolve()
            results.append(_write_surface(base / "skills" / SKILL_DIRNAME, str(base), content))
        else:
            root = Path(project_root).resolve() if project_root is not None else Path.cwd()
            if codex:
                results.append(
                    _write_surface(root / PORTABLE_SKILL_REL, ".agents/skills (portable)", content)
                )
            if claude:
                results.append(
                    _write_surface(root / CLAUDE_SKILL_REL, ".claude/skills (Claude Code)", content)
                )
    except PermissionError as e:
        print(f"\n✗ Permission denied: {e}", file=sys.stderr)
        sys.exit(1)
    except OSError as e:
        print(f"\n✗ Installation failed: {e}", file=sys.stderr)
        sys.exit(1)

    _print_install_summary(results)
    return results


def _print_install_summary(results: list[InstallResult]) -> None:
    print("\nFlowmark skill installation:")
    for r in results:
        if r.action == "blocked-newer":
            print(f"  ‼️  {r.surface}: {r.path} was generated by a NEWER flowmark.")
            print("      Upgrade flowmark (e.g. `uv tool install --upgrade flowmark`) and retry.")
        else:
            print(f"  ✅ {r.action:<9} {r.surface}: {r.path}")
    print()


def main() -> None:
    """Command-line interface for skill installation.

    Can be run directly for testing:
        python -m flowmark.skill
        python -m flowmark.skill --agent-base ./.claude
    """
    import argparse

    parser = argparse.ArgumentParser(
        description="Install flowmark Claude Code skill",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s                        # Project-local: .agents/skills + .claude/skills
  %(prog)s --agent-base ~/.claude # Single explicit base (global): ~/.claude/skills
        """,
    )

    parser.add_argument(
        "--agent-base",
        dest="agent_base",
        metavar="DIR",
        help="agent config directory (defaults to ~/.claude)",
    )

    args = parser.parse_args()

    install_skill(agent_base=args.agent_base)


if __name__ == "__main__":
    main()
