"""Private source-preservation primitives for Flowmark's formatting pipeline."""

from flowmark.preservation.bridge import (
    ESCAPE_MARKER,
    INDEX_SCALAR_END,
    INDEX_SCALAR_START,
    INDEX_WIDTH,
    TOKEN_END,
    TOKEN_LENGTH,
    TOKEN_START,
    InvalidTokenError,
    ProtectedSource,
    encode_token,
    parse_token,
    protect_source,
    restore_source,
)
from flowmark.preservation.model import (
    Candidate,
    ContainerContext,
    InvalidRegionError,
    InvalidUtf8Error,
    NormalizedSource,
    PreservationError,
    ProtectedRegion,
    RegionForm,
    RegionKind,
    validate_regions,
)
from flowmark.preservation.normalization import (
    finalize_output,
    normalize_source,
    scalar_width,
    scalar_widths,
)
from flowmark.preservation.registry import (
    BLOCK_RECOGNIZER_BY_KIND,
    BUILTIN_BLOCK_RECOGNIZERS,
    BUILTIN_RECOGNIZERS,
    RECOGNIZER_BY_KIND,
    BlockRecognizerDescriptor,
    BlockRuleKind,
    RecognizerDescriptor,
)
from flowmark.preservation.scanner import (
    ContainerLine,
    InlineScope,
    OpaqueBlock,
    build_container_view,
    scan_protected_regions,
)

__all__ = [
    "BLOCK_RECOGNIZER_BY_KIND",
    "BUILTIN_BLOCK_RECOGNIZERS",
    "BUILTIN_RECOGNIZERS",
    "RECOGNIZER_BY_KIND",
    "BlockRecognizerDescriptor",
    "BlockRuleKind",
    "Candidate",
    "ContainerContext",
    "ContainerLine",
    "InlineScope",
    "InvalidRegionError",
    "InvalidTokenError",
    "InvalidUtf8Error",
    "NormalizedSource",
    "OpaqueBlock",
    "PreservationError",
    "ProtectedRegion",
    "ProtectedSource",
    "RecognizerDescriptor",
    "RegionForm",
    "RegionKind",
    "ESCAPE_MARKER",
    "INDEX_SCALAR_END",
    "INDEX_SCALAR_START",
    "INDEX_WIDTH",
    "TOKEN_END",
    "TOKEN_LENGTH",
    "TOKEN_START",
    "build_container_view",
    "encode_token",
    "finalize_output",
    "normalize_source",
    "parse_token",
    "protect_source",
    "restore_source",
    "scalar_width",
    "scalar_widths",
    "scan_protected_regions",
    "validate_regions",
]
